if(NOT ANDROID)
    return()
endif()
if(NOT DEFINED COMBO_VCPKG_PREFIX OR NOT EXISTS "${COMBO_VCPKG_PREFIX}/include")
    message(FATAL_ERROR "Set COMBO_VCPKG_PREFIX to the prepared arm64-android vcpkg prefix")
endif()
set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)
list(PREPEND CMAKE_PREFIX_PATH "${COMBO_VCPKG_PREFIX}")
list(PREPEND CMAKE_FIND_ROOT_PATH "${COMBO_VCPKG_PREFIX}")
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(USE_OPENGLES ON CACHE BOOL "Android GLES3" FORCE)
set(ENABLE_SCRIPTING OFF CACHE BOOL "No desktop runtime compiler on Android" FORCE)
set(SDL_SHARED ON CACHE BOOL "One SDL runtime" FORCE)
set(SDL_STATIC OFF CACHE BOOL "Do not duplicate SDL" FORCE)
set(SDL_TEST OFF CACHE BOOL "No SDL tests" FORCE)
set(SDL_TESTS OFF CACHE BOOL "No SDL tests" FORCE)
set(SDL2_DISABLE_INSTALL ON CACHE BOOL "No SDK installation" FORCE)
find_package(PNG CONFIG REQUIRED)
if(NOT TARGET png)
    add_library(png ALIAS PNG::PNG)
endif()
find_package(Ogg CONFIG REQUIRED)
find_package(Vorbis CONFIG REQUIRED)
find_package(Opus CONFIG REQUIRED)
find_package(OpusFile CONFIG REQUIRED)
if(TARGET OpusFile::opusfile AND NOT TARGET Opusfile::Opusfile)
    add_library(Opusfile::Opusfile ALIAS OpusFile::opusfile)
endif()
include(FetchContent)
FetchContent_Declare(SDL2 GIT_REPOSITORY https://github.com/libsdl-org/SDL.git GIT_TAG release-2.32.10 GIT_SHALLOW TRUE OVERRIDE_FIND_PACKAGE)
FetchContent_MakeAvailable(SDL2)
set(SDL2NET_SAMPLES OFF CACHE BOOL "No SDL_net samples" FORCE)
set(SDL2NET_INSTALL OFF CACHE BOOL "No SDK installation" FORCE)
set(BUILD_SHARED_LIBS ON)
FetchContent_Declare(SDL2_net GIT_REPOSITORY https://github.com/libsdl-org/SDL_net.git GIT_TAG release-2.2.0 GIT_SHALLOW TRUE OVERRIDE_FIND_PACKAGE)
FetchContent_MakeAvailable(SDL2_net)
set(BUILD_SHARED_LIBS OFF)
add_compile_definitions(IMGUI_IMPL_OPENGL_ES3)
add_link_options("-Wl,-z,max-page-size=16384" "-Wl,-z,common-page-size=16384")
